"""update: blog model

Revision ID: 29d04546f502
Revises: 1cb8fdb613de
Create Date: 2023-06-28 23:07:02.062513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d04546f502'
down_revision = '1cb8fdb613de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_content', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('featured')
        batch_op.drop_column('short_content')

    # ### end Alembic commands ###
